import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's github repository
*/
`;

const prod = process.argv[2] === "production";

// Packages Obsidian bundles and exposes to plugins at runtime. Bundling a
// second copy of any of these breaks CodeMirror's singleton assumptions
// (facets, state, syntax tree), so they must stay external. NOTE: the
// `@codemirror/lang-*` packages are NOT in this list — Obsidian does not ship
// them, so they get bundled into main.js.
const cmExternals = [
	"@codemirror/state",
	"@codemirror/view",
	"@codemirror/language",
	"@codemirror/commands",
	"@codemirror/search",
	"@codemirror/autocomplete",
	"@codemirror/lint",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
];

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: ["obsidian", "electron", ...cmExternals, ...builtinModules],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	platform: "node",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
